# Generated by Django 2.2 on 2020-01-12 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200112_0839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pages',
            name='timne',
        ),
    ]
